### ISSUE TITLE
Not working on Node 6.10

### ISSUE THREAD

**Issue by mfrye** [nol13/fuzzball.js#3]
```
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
    at TLSSocket.d (/.../node_modules/fuzzball/lib/difflib.js:5:18962)
    at TLSSocket.f.emit (/.../node_modules/fuzzball/lib/difflib.js:5:18023)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
```

Any idea on why this isn't loading properly? I have to use 6.10 for Lambda support...

**Comment by nol13** [comment]
does using npm difflib fix this?

**Comment by nol13** [comment]
also any example code? couldn't replicate locally under 6.10.3, but have had issue with the difflib import.

really would probably rather just pull the needed pieces out of it or rewrite them and save on file size

**Comment by nol13** [comment]
Could you try pulling from this branch and see if you have same issue?

https://github.com/nol13/fuzzball.js/tree/difflib-rework

**Comment by nol13** [comment]
Ok did a bit of testing, doing some basic stuff on lambda seems ok as far as I can tell. Are you sure not running out of memory or timing out? Running on lambda was actually part of original use case for making this, so want to make sure it works well.

Did go ahead and pull out just SequenceMatcher from difflib though, had kind of been on todo list for a while anyway.

**Comment by nol13** [comment]
Ya I'm impatient I guess. ;) Still happens with 1.1.1?

Original change I did to get it working with react-native packager was taking the dist/difflib-browser.js file from difflib and adding a module.exports to it, then swapping it in place of the standard npm require. Hacky but seemed to work, but I guess not that surprising in hindsight if it caused issues. Hoping new cut-down version better, but if not def would like to figure out whats up. Would prefer not to go back to npm version that I know breaks stuff though.
